### ISSUE TITLE
Architecture issue: ResponderSimulatorTask singleton bean and scaling out.  

### ISSUE THREAD

**Issue by whitingjr** [wildfly-extras/first-responder-demo#7]
The bean [ResponderSimulatorTask](https://github.com/wildfly-extras/first-responder-demo/blob/main/backend/src/main/java/org/cajun/navy/model/responder/ResponderSimulatorTask.java) is annotated with @Singleton.
 The singleton bean has the [doMoveResponderLocation](https://github.com/wildfly-extras/first-responder-demo/blob/main/backend/src/main/java/org/cajun/navy/model/responder/ResponderSimulatorTask.java#L21-L27) method that retrieves all the MissionEntity objects from the database.

 Consider what happens when more than 1 EAP instance is created. Each EAP instance will use it's own ResponderSimulatorTask bean instance. Each bean will retrieve and be processing either an identical or overlapping [list](https://github.com/wildfly-extras/first-responder-demo/blob/main/backend/src/main/java/org/cajun/navy/model/responder/ResponderSimulatorTask.java#L22) of MissionEntity objects. This will cause the callee method [MissionService.doResponderNextMove](https://github.com/wildfly-extras/first-responder-demo/blob/main/backend/src/main/java/org/cajun/navy/service/MissionService.java#L142-L196) to cause the database to raise OptimisticLockExceptions or some sort of PSQLException to the same effect.

**Comment by sshaaf** [comment]
#12 has a fix for this for now, by enabling processing on one node only. This will work, but consideration needs to be made to do this either async/reactive based on the stream that is received when a mission is created or using and MDB etc.

**Comment by whitingjr** [comment]
Closed as this has been resolved by providing an option to disable the Scheduled task.
