### ISSUE TITLE
Architecture issue: Using a Singleton bean in a scalable application.

### ISSUE THREAD

**Issue by whitingjr** [wildfly-extras/first-responder-demo#8]
Using a Singleton bean in an application that is intended to scale out is flawed. For 2 reasons:

-  Becomes a bottleneck that will limit the maximum rate of request processing on a single server instance
-  Limits the number of EAP server instance. See #7 

 Instead it is better to architect the system to use work stealing or a messaging solution that supports JMS specification. Allowing the capability for EJB Message Driven Beans in EAP to process MissionEntity objects in the first responder application.
 This is crucial in a distributed system with more than 1 EAP server instance.

**Comment by sshaaf** [comment]
The intention was not to scale this out. But with the current use case it makes sense
I see a PR is made #12 . At this point that is short term solution. An MDB could be a solution.

**Comment by whitingjr** [comment]
@sshaaf sorry, you must be wondering where I am coming from with this issue. I had meant to create an issue on a forked downstream repository. Where the intended requirements and use of first responder demo is different.
